### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by fabrizio-turchi** [ucoProject/UCO-Utility-Pre-0.7.0-Validator#1]
Hello,

first very thank indeed for this utility, it's astounding!

I run the tool in UCO 0.4 and a small JSON-LD file and it raised a short list of errors that I don't understand how to fix:
Data Error: Class <observable:CyberItem> malformed case data: BNode <_:N3e031842e091475aa5b45555307f3331> has no datatypes.
Data Error: N174ffae3fd074a06b49239526daf3c56 has no ranges.
Constraint Error: Class <core:Relationship> Property <core:kindOfRelationship> property has 2 values but must have at most 1.

and a few more similar to the above ones. The last error is disorienting because I have other uco-core:Relationship objects with similar value for the property uco-core:kindOfRelationship.

I can provide the JSON-LD file in case of need.

Best regards

**Comment by stanbernsteen** [comment]
The BNode error is a bug in the program.  The Validator does not support ordered lists (oso:slots and olo:items), and their BNodes confuse the tool.   The next release, Version 1.1, will still not support ordered lists.  Please be patient; it's on my bug list and will be fixed in Version 1.2.

If  your data has two objects with the same @id, their properties and their values are combined into a single object.  That could cause properties to look like they have more values than you expect.
