### ISSUE TITLE
Error messages (UFED report)

### ISSUE THREAD

**Issue by fabrizio-turchi** [ucoProject/UCO-Utility-Pre-0.7.0-Validator#6]
I'm not able to interpret the following errors (CASE 0.3/UCO 0.5):

- Constraint Error: Line 18, Class <uco-core:Bundle> Property <uco-core:object> Property's value kb:61755497-d6fc-4b82-835a-11786749f589 is a <uco-investigation:ProvenanceRecord> but must be a <uco-core:UcoObject>.
- Data Error: Line 525940, Class <uco-observable:MessageThreadFacet> BNode <N620012e0e55347568ae08b7947d5e5c7> has no datatypes.
- Data Error: Line 526315, Class <uco-observable:MessageFacet> Missing link <file:///var/folders/cv/gm3g5czj3v7879vwc34l0xt80000gn/T/tmpgg72eunb/ID System Message NOT_FOUND>.
- Data Error: Line 550736, Class <uco-role:Role> Class not in ontology.
- Constraint Error: Line 550741, Class <uco-observable:ObservableRelationship> Property <uco-core:target> Property's value kb:84e963c9-626f-4299-8fc3-8c9d78b7ac75 is a <uco-role:Role> but must be a <uco-core:UcoObject>.
- Data Error: Line 550785, Class <uco-investigation:ProvenanceRecord> Class not in ontology.

Please ignore the additional errors, correctly raised by the Tool, I'll be discussing them in the next AC-meeting. Thanks!
[19_UFED_ANDROID_CROSSOVER.zip](https://github.com/ucoProject/UCO-Utility-Pre-0.7.0-Validator/files/6336210/19_UFED_ANDROID_CROSSOVER.zip)

**Comment by stanbernsteen** [comment]
There are several problems here.

(1)  In 19_UFED_ANDROID_CROSSOVER.json, the @context defines case-investigation but the data uses uco-investigation.  Also, the @prefix does not define uco-role but the data uses uco-role.

(2)  In the ontolgy, in uco-core-da.ttl, we have this line:
      @prefix investigation: <https://unifiedcyberontology.org/ontology/uco/investigation#> .
It should be this instead 
      @prefix investigation: <https://caseontology.org/ontology/case/investigation#> .
This confuses Ontospy so that it does not think the investigation classes are a subclass of UcoObject.

(3)  The tool does not support ordered lists (olo:slot, olo:item, etc.)
Because of the internal node structure, adding olo support is a major task and could take me take a week.   In the interim, I could patch the tool to catch the problem and print a civilized "Unsupported Feature" message instead of all those meaningless BNode messages.  I await further guidance from my management.

**Comment by fabrizio-turchi** [comment]
excellent, thanks!
